# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [279]:
# No code solution (reading)
import torch

In [280]:
X1 = torch.tensor(
    [
        [9, 6],
        [3, 7],
        [2, 1]
    ],
    dtype=torch.float16,
    device='cuda'
)

In [281]:
X2 = torch.tensor(
    [
        [1,4, 6],
        [1,4, 6]
    ],
    dtype=torch.float16,
    device='cuda'
)

In [282]:
X1

tensor([[9., 6.],
        [3., 7.],
        [2., 1.]], device='cuda:0', dtype=torch.float16)

In [283]:
X2

tensor([[1., 4., 6.],
        [1., 4., 6.]], device='cuda:0', dtype=torch.float16)

In [284]:
print(X1.shape, X2.shape)

torch.Size([3, 2]) torch.Size([2, 3])


In [285]:
torch.mm(X1,X2)

tensor([[15., 60., 90.],
        [10., 40., 60.],
        [ 3., 12., 18.]], device='cuda:0', dtype=torch.float16)

In [286]:
X1 @ X2

tensor([[15., 60., 90.],
        [10., 40., 60.],
        [ 3., 12., 18.]], device='cuda:0', dtype=torch.float16)

### 2. Create a random tensor with shape `(7, 7)`.


In [288]:
# Import torch


# Create random tensor
tensor_2 = torch.rand(7,7)
tensor_2

tensor([[0.8866, 0.2997, 0.6329, 0.6164, 0.0562, 0.3922, 0.2823],
        [0.7519, 0.8442, 0.7106, 0.3314, 0.8299, 0.6466, 0.4240],
        [0.4415, 0.4576, 0.5639, 0.9992, 0.7985, 0.7247, 0.8608],
        [0.6405, 0.1202, 0.1931, 0.0465, 0.3040, 0.4827, 0.4850],
        [0.0036, 0.2199, 0.9126, 0.1490, 0.9177, 0.8823, 0.4940],
        [0.8631, 0.3939, 0.9699, 0.7821, 0.6495, 0.0792, 0.4390],
        [0.1384, 0.3831, 0.2257, 0.4526, 0.6579, 0.4438, 0.4430]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [290]:
# Create another random tensor
tensor_3 = torch.rand(1,7)

# Perform matrix multiplication 
torch.mm(tensor_2,tensor_3.T)

tensor([[2.0260],
        [2.0256],
        [2.4786],
        [1.2702],
        [1.3171],
        [2.5890],
        [1.1526]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [291]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor_2 = torch.rand(7,7)
tensor_3 = torch.rand(1,7)

# Perform matrix multiplication
torch.mm(tensor_2,tensor_3.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [297]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [300]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'

# Create two random tensors on GPU
tensor_6 = torch.rand(2,3, device=device)
tensor_7 = torch.rand(2,3, device=device)


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [303]:
# Perform matmul on tensor_A and tensor_B
tensor_7 = torch.mm(tensor_6, tensor_7.T)

### 8. Find the maximum and minimum values of the output of 7.

In [305]:
# Find max
tensor_7.max()

# Find min
tensor_7.min()

tensor(0.2786, device='cuda:0')

### 9. Find the maximum and minimum index values of the output of 7.

In [307]:
# Find arg max
tensor_7.argmax()

# Find arg min
tensor_7.argmin()

tensor(0, device='cuda:0')


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [312]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_10 = torch.rand((1,1,1,10))

# Remove single dimensions
tensor_10s = tensor_10.squeeze()

# Print out tensors and their shapes
tensor_10s.shape, tensor_10.shape

(torch.Size([10]), torch.Size([1, 1, 1, 10]))